# This file was generated by GoReleaser. DO NOT EDIT.
cask "memlint" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "19f016045f97d16f9d9358c4e82efd8bb2db444a5e88d1c8e76ae0670fdf1be1"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "426b365cb9525152b0452db6e9c1ec2732687eea0f927ff941f051b089b805a7"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "06a15f8f7f86f5e914e8b3999b3a9e73bb9550b4f1b5e25561607127bc766aad"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a1199c8da76cdbd471209ecd4379cce6759081ba16b5440aa3258555b6322b1"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "memlint"
  desc "Invariant checker for file-based agent memory"
  homepage "https://github.com/frankbesch/memlint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memlint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memlint"]
    end
  end

  # No zap stanza required
end
