# This file was generated by GoReleaser. DO NOT EDIT.
cask "memlint" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "d70029632447c229fc3b57cd854602e28dbcd0b71b9d028efa3b8cd9854e423c"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ccfe0cab0306099c474093267476f808575a3dfb26a0d68fdac27a3b66dd6db8"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "894f721fdcc6f7ce4a2a7d1a40f177de1be4d3d6a269b20111cd61c563ec82f7"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dab448767c09f4104b6027980dec93314c580d47f3dcb3e4bada269c2d3456a2"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "memlint"
  desc "Invariant checker for file-based agent memory"
  homepage "https://github.com/frankbesch/memlint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memlint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memlint"]
    end
  end

  # No zap stanza required
end
