# This file was generated by GoReleaser. DO NOT EDIT.
cask "memlint" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "4e4116ea7914158c9ffa93b1c530f5876fe1db6b9b0eb721d51db5f6240aadf6"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "810607ed02c7b5932829c188d88f770bb49687f6a0032a8ee3368e7c06328528"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84061d8ad65a656cd2dbfde23e1db43026b73e9ecd810497bf5bb19f7b1b0ca7"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "49902ceb319c281e51046a4c94915addbcb3606524f5c485b05c4e5c8744f3dc"
      url "https://github.com/frankbesch/memlint/releases/download/v#{version}/memlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "memlint"
  desc "Invariant checker for file-based agent memory"
  homepage "https://github.com/frankbesch/memlint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memlint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memlint"]
    end
  end

  # No zap stanza required
end
