# This file was generated by GoReleaser. DO NOT EDIT.
cask "memvet" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "384fd0e6a416977f93b57a954bbbdbf7f04f925df8aa3a1602db419ae339e3a1"
      url "https://github.com/frankbesch/memvet/releases/download/v#{version}/memvet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b3acd6542c4ba15dffd234df1b5fe817e9c42bbbf0c9ac293d9a49e0d59c3e9"
      url "https://github.com/frankbesch/memvet/releases/download/v#{version}/memvet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "52f3c01773b9a8356858f4da1c9a691d2e43c47fac96d8b74f12cf7aecdfe985"
      url "https://github.com/frankbesch/memvet/releases/download/v#{version}/memvet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff3fda809f4f0fcabd495b14664f95f699be804d30dc83b7d9628af1f3e7e64e"
      url "https://github.com/frankbesch/memvet/releases/download/v#{version}/memvet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "memvet"
  desc "Invariant checker for file-based agent memory"
  homepage "https://github.com/frankbesch/memvet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memvet"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memvet"]
    end
  end

  # No zap stanza required
end
